import React from "react";

const NotFound = () => {
  return (
    <div>
      <h1>
        NotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFound
      </h1>
      <h1>
        NotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFound
      </h1>
      <h1>
        NotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFound
      </h1>
      <h1>
        NotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFound
      </h1>
      <h1>
        NotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFound
      </h1>
      <h1>
        NotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFound
      </h1>
      <h1>
        NotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFoundNotFound
      </h1>
    </div>
  );
};

export default NotFound;
